
import os
import re

file_path = r'c:\corvo-bot-corrigido\corvo.js'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_line = -1
end_line = -1

for i, line in enumerate(lines):
    if "body: { text: '*Resultados da metadinha* 💝 ↴' }," in line:
        start_line = i + 1
    if "site(quote, 40, 40)" in line:
        end_line = i
        break

if start_line != -1 and end_line != -1:
    print(f"Fixing lines {start_line+1} to {end_line+1}")
    
    replacement = [
        '                  carouselMessage: {\n',
        '                    cards: [\n',
        '                      {\n',
        '                        header: {\n',
        '                          hasMediaAttachment: true,\n',
        '                          imageMessage: maleMedia.imageMessage\n',
        '                        },\n',
        '                        body: { text: "• Perfil Masculino 🕊️" },\n',
        '                        footer: { text: NomeDoBot },\n',
        '                        nativeFlowMessage: { buttons: [] }\n',
        '                      },\n',
        '                      {\n',
        '                        header: {\n',
        '                          hasMediaAttachment: true,\n',
        '                          imageMessage: femaleMedia.imageMessage\n',
        '                        },\n',
        '                        body: { text: "• Perfil Feminino 🌸" },\n',
        '                        footer: { text: NomeDoBot },\n',
        '                        nativeFlowMessage: { buttons: [] }\n',
        '                      }\n',
        '                    ]\n',
        '                  }\n',
        '                }\n',
        '              }, { quoted: info });\n',
        '\n',
        '              await corvo.relayMessage(from, msg.message, { messageId: msg.key.id });\n',
        '\n',
        '            } catch (e) {\n',
        "              console.log('[METADINHA ERROR]', e?.message || e);\n",
        '              reply("❌ Erro ao buscar metadinha.");\n',
        '            }\n',
        '            break;\n',
        '\n',
        "          case 'ytvideo':\n",
        "          case 'ytmp4':\n",
        "          case 'video':\n",
        "          case 'playvideo':\n",
        "          case 'playvid':\n",
        "          case 'playmp4': {\n",
        '            try {\n',
        '              if (!q) return reply(`🎬 Exemplo: ${prefix}playvideo bad liar`)\n',
        '              await reagir(from, "⏳")\n',
        '              \n',
        '              const res = await axios.get(`https://api.spiderx.com.br/api/downloads/play-video?search=${encodeURIComponent(q)}&api_key=${CONFIG_ADMIN.SPIDERX_API_KEY}`);\n',
        '              const data = res.data;\n',
        '              \n',
        '              if (!data || !data.url) return reply("❌ Não encontrei vídeo para essa busca nos registros do SPIDERX.");\n',
        '              \n',
        '              const { title, thumbnail, total_duration_in_seconds, url } = data;\n',
        '              const duracao = `${Math.floor(total_duration_in_seconds / 60)}:${String(total_duration_in_seconds % 60).padStart(2, "0")}`;\n',
        '              \n',
        '              const caption = `🎬 *𝐒𝐏𝐈𝐃𝐄𝐑𝐗 𝐕𝐈𝐃𝐄𝐎* 🎬\\n\\n📌 *Título:* ${title}\\n⏱️ *Duração:* ${duracao}\\n\\n*Enviando vídeo...*`;\n',
        '              \n',
        '              await corvo.sendMessage(from, { image: { url: thumbnail }, caption }, { quoted: info });\n',
        '              \n',
        '              const videoBuffer = await getBuffer(url);\n',
        '              await corvo.sendMessage(from, { video: videoBuffer, caption: `✅ ${title}`, mimetype: "video/mp4" }, { quoted: info });\n',
        '              \n',
        '              await reagir(from, "✅");\n',
        '            } catch (e) {\n',
        '              console.error("[VIDEO-ERROR]", e.message);\n',
        '              reply("❌ Erro ao processar vídeo: " + e.message);\n',
        '            }\n',
        '          }\n',
        '          break;\n',
        '\n',
        "          case 'bratvid':\n",
        "          case 'iphonequote':\n",
        "          case 'fakequote': {\n",
        '            try {\n',
        '              var quoted = info.message?.extendedTextMessage?.contextInfo?.quotedMessage\n',
        '              var participant = info.message?.extendedTextMessage?.contextInfo?.participant || sender\n',
        '\n',
        '              var texto = q?.trim()\n',
        '\n',
        '              if (!texto && quoted) {\n',
        '                texto =\n',
        '                  quoted?.conversation ||\n',
        '                  quoted?.extendedTextMessage?.text ||\n',
        '                  quoted?.imageMessage?.caption ||\n',
        '                  quoted?.videoMessage?.caption ||\n',
        '                  ""\n',
        '              }\n',
        '\n',
        '              if (!texto) {\n',
        '                return reply(`Exemplo:\\n${prefix}bratvid halo\\n\\nOu responda uma mensagem com:\\n${prefix}bratvid`)\n',
        '              }\n',
        '\n',
        '              await reagir(from, "📱")\n',
        '\n',
        '              var nomeAutor = pushname || "Usuário"\n',
        '\n',
        '              var bodyApi = {\n',
        '                type: "quote",\n',
        '                format: "png",\n',
        '                backgroundColor: "#111111",\n',
        '                width: 512,\n',
        '                height: 768,\n',
        '                scale: 2,\n',
        '                messages: [\n',
        '                  {\n',
        '                    entities: [],\n',
        '                    avatar: true,\n',
        '                    from: {\n',
        '                      id: 1,\n',
        '                      name: nomeAutor\n',
        '                    },\n',
        '                    text: texto,\n',
        '                    replyMessage: {}\n',
        '                  }\n',
        '                ]\n',
        '              }\n',
        '\n',
        '              var res = await axios.post(\n',
        '                "https://bot.lyo.su/quote/generate",\n',
        '                bodyApi,\n',
        '                {\n',
        '                  headers: { "Content-Type": "application/json" },\n',
        '                  timeout: 20000\n',
        '                }\n',
        '              )\n',
        '\n',
        '              if (!res?.data?.result?.image) {\n',
        '                return reply("❌ Não consegui gerar a quote.")\n',
        '              }\n',
        '\n',
        '              var quoteBuffer = Buffer.from(res.data.result.image, "base64")\n',
        '\n',
        "              var JimpModule = require('jimp')\n",
        '              var Jimp = JimpModule.Jimp || JimpModule\n',
        '\n',
        '              var bg = await Jimp.read("https://files.catbox.moe/akgwu2.jpg")\n',
        '              bg.resize(1080, 1920)\n',
        '              bg.blur(6)\n',
        '              bg.brightness(-0.25)\n',
        '\n',
        '              var quote = await Jimp.read(quoteBuffer)\n',
        '              quote.resize(760, Jimp.AUTO)\n',
        '\n',
        '              var moldura = new Jimp({ width: 840, height: quote.bitmap.height + 80, color: 0x00000000 })\n',
        '\n',
        '              var branco = 0xffffffff\n',
        '\n',
        '              // linhas/cantos brancos estilo da imagem\n',
        '              for (var i = 0; i < 160; i++) {\n',
        '                moldura.setPixelColor(branco, 20 + i, 20)\n',
        '                moldura.setPixelColor(branco, 20, 20 + i)\n',
        '\n',
        '                moldura.setPixelColor(branco, moldura.bitmap.width - 21 - i, 20)\n',
        '                moldura.setPixelColor(branco, moldura.bitmap.width - 21, 20 + i)\n',
        '\n',
        '                moldura.setPixelColor(branco, 20 + i, moldura.bitmap.height - 21)\n',
        '                moldura.setPixelColor(branco, 20, moldura.bitmap.height - 21 - i)\n',
        '\n',
        '                moldura.setPixelColor(branco, moldura.bitmap.width - 21 - i, moldura.bitmap.height - 21)\n',
        '                moldura.setPixelColor(branco, moldura.bitmap.width - 21, moldura.bitmap.height - 21 - i)\n',
        '              }\n',
        '\n',
        '              moldura.composite(quote, 40, 40)\n'
    ]
    
    new_lines = lines[:start_line] + replacement + lines[end_line+1:]
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print("Repair complete.")
else:
    print(f"Could not find anchors: start_line={start_line}, end_line={end_line}")

# Fix the duplicate play block at the end if it exists
# (Wait, I should check if there are other corrupted areas first)
